### ISSUE TITLE
Bug making CSR by OpenSSL

### ISSUE THREAD

**Issue by Shokrian** [aws/aws-rfdk#1039] opened 2023-05-05 21:55 UTC
Please help me to solve the following error problem.

Can you write more than 64 characters in OpenSSL command?

I get the following error:
problems making Certificate Request
3555938678416:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:158:maxsize=64

### Environment

  - **CDK CLI Version      :**
  - **CDK Framework Version:**
  - **RFDK Version:**
  - **Deadline Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by ddneilson** [comment] 2023-05-15 22:21
Sorry for the delay. Can you share the RFDK code that you used to produce the aforementioned error message?

Just the invocation of the Certificate construct is sufficient.

**Comment by ddneilson** [comment] 2023-05-16 20:14
Duplicate of https://github.com/aws/aws-rfdk/issues/220

**Closed as completed by ddneilson** 2023-05-16 20:14 UTC
Labels: bug, duplicate, needs-triage

**Comment by Shokrian** [comment] 2023-05-17 09:07
Hello Mr. DanielI will send you the fa.cnf filePlease create 2 files for me with OpenSSl:1- Fa.csr2-fa.keythank you for Help me

    On Tuesday, May 16, 2023 at 11:44:40 PM GMT+3:30, Daniel Neilson ***@***.***> wrote:  
 
 


Closed #1039 as completed.

**Comment by Shokrian** [comment] 2023-05-17 09:13
Because the name of the organization is more than 64 characters and 2 files Fa.csr and Fa.key are not generated by OpenSSL.In addition, the name of the organization in line 3.OU, 2.OU and 1.OU must be in Persian language.thank you very muchYours sincerelyMr. Shokrian

    On Wednesday, May 17, 2023 at 12:37:31 PM GMT+3:30, ***@***.*** ***@***.***> wrote:  
 
  Hello Mr. DanielI will send you the fa.cnf filePlease create 2 files for me with OpenSSl:1- Fa.csr2-fa.keythank you for Help me

    On Tuesday, May 16, 2023 at 11:44:40 PM GMT+3:30, Daniel Neilson ***@***.***> wrote:  
 
 


Closed #1039 as completed.

**Comment by Shokrian** [comment] 2023-05-17 09:27
HelloMr. DanielI sent the CSR creation error message in the attached fileYours sincerelyMr. Shokrian

    On Wednesday, May 17, 2023 at 12:43:23 PM GMT+3:30, ***@***.*** ***@***.***> wrote:  
 
  Because the name of the organization is more than 64 characters and 2 files Fa.csr and Fa.key are not generated by OpenSSL.In addition, the name of the organization in line 3.OU, 2.OU and 1.OU must be in Persian language.thank you very muchYours sincerelyMr. Shokrian

    On Wednesday, May 17, 2023 at 12:37:31 PM GMT+3:30, ***@***.*** ***@***.***> wrote:  
 
  Hello Mr. DanielI will send you the fa.cnf filePlease create 2 files for me with OpenSSl:1- Fa.csr2-fa.keythank you for Help me

    On Tuesday, May 16, 2023 at 11:44:40 PM GMT+3:30, Daniel Neilson ***@***.***> wrote:  
 
 


Closed #1039 as completed.
