### ISSUE TITLE
Python: MongoDbPostInstallSetup error when setting up MongoDbUsers with MongoDbX509User

### ISSUE THREAD

**Issue by apzentral** [aws/aws-rfdk#321] opened 2021-02-21 08:22 UTC
I use example code from examples/deadline/All-In-AWS-Infrastructure-Basic/python by setting config.py self.deploy_mongo_db: bool = True this causing the error when trying to set up MongoDbUsers with MongoDbX509User in MongoDbPostInstallSetup.

### Reproduction Steps

in `storage_tier.py`

```python
        server_cert = X509CertificatePem(
            self,
            'MongoCert',
            subject=DistinguishedName(
                cn=f'mongo.{props.dns_zone.zone_name}',
                o='RFDK-Sample',
                ou='MongoServer'
            ),
            signing_certificate=props.root_ca
        )

        client_cert = X509CertificatePem(
            self,
            'DeadlineMongoCert',
            subject=DistinguishedName(
                cn='SampleUser',
                o='RFDK-Sample',
                ou='MongoClient'
            ),
            signing_certificate=props.root_ca
        )
        client_pkcs12 = X509CertificatePkcs12(
            self,
            'DeadlineMongoPkcs12',
            source_certificate=client_cert
        )

        mongo_db = MongoDbInstance(
            self,
            'MongoDb',
            vpc=props.vpc,
            # vpc_subnets=mongo_vpc_subnet,
            key_name=props.key_pair_name,
            instance_type=props.database_instance_type,
            mongo_db=MongoDbApplicationProps(
                user_sspl_acceptance=props.accept_sspl_license,
                version=MongoDbVersion.COMMUNITY_3_6,
                hostname='mongo',
                dns_zone=props.dns_zone,
                server_certificate=server_cert
            )
        )

        _mongo_db_post_install_setup = MongoDbPostInstallSetup(
            self,
            'MongoDbPostInstall',
            vpc=props.vpc,
            # vpc_subnets=mongo_vpc_subnet,
            mongo_db=mongo_db,
            users=MongoDbUsers(
                x509_auth_users=[
                    MongoDbX509User(
                        certificate=client_cert,
                        roles=json.dumps([
                            {
                                'role': 'readWriteAnyDatabase',
                                'db': 'admin'
                            },
                            {
                                'role': 'clusterMonitor',
                                'db': 'admin'
                            }
                        ])
                    )
                ]
            )
        )
```

### Error Log

jsii.errors.JSIIError: user.certificate.grantRead is not a function

### Environment

  - **CDK CLI Version      : 1.86.0**
  - **CDK Framework Version: 1.86.0**
  - **RFDK Version: 0.25.0**
  - **Deadline Version: latest release**
  - **Node.js Version: v14.15.5** 
  - **OS               : Windows 10 with WSL2 Ubuntu**
  - **Language (Version): Python 3.8.5** 

### Other

jsii.errors.JavaScriptError:
  TypeError: user.certificate.grantRead is not a function
      at /tmp/jsii-kernel-OgoUTK/node_modules/aws-rfdk/lib/core/lib/mongodb-post-install.js:99:115
      at Array.forEach (<anonymous>)
      at new MongoDbPostInstallSetup (/tmp/jsii-kernel-OgoUTK/node_modules/aws-rfdk/lib/core/lib/mongodb-post-install.js:99:82)
      at /tmp/tmp0toclf9q/lib/program.js:2720:58
      at Kernel._wrapSandboxCode (/tmp/tmp0toclf9q/lib/program.js:3148:24)
      at Kernel._create (/tmp/tmp0toclf9q/lib/program.js:2720:34)
      at Kernel.create (/tmp/tmp0toclf9q/lib/program.js:2461:29)
      at KernelHost.processRequest (/tmp/tmp0toclf9q/lib/program.js:9457:36)
      at KernelHost.run (/tmp/tmp0toclf9q/lib/program.js:9420:22)
      at Immediate._onImmediate (/tmp/tmp0toclf9q/lib/program.js:9421:46)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/app.py", line 133, in <module>
    main()
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/app.py", line 91, in main
    storage = storage_tier.StorageTierMongoDB(app, 'StorageTier', props=storage_props, env=env)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/storage_tier.py", line 234, in __init__
    _mongo_db_post_install_setup = MongoDbPostInstallSetup(
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/aws_rfdk/__init__.py", line 2844, in __init__
    jsii.create(MongoDbPostInstallSetup, self, [scope, id, props])
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 265, in create
    response = self.provider.create(
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 348, in create
    return self._process.send(request, CreateResponse)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 330, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: user.certificate.grantRead is not a function

--- 

This is :bug: Bug Report

**Comment by apzentral** [comment] 2021-02-21 08:26
I also try with

```
> cdk --version
1.90.1 (build 0aee440)
```

and the error is the same as above.

Thank you very much for looking into this.

**Comment by ddneilson** [comment] 2021-02-22 15:33
Thanks for the report, and the great reproduction details!

**Comment by ddneilson** [comment] 2021-02-22 15:58
This is a mistake in our example. It looks like there was an error when we converted it from Typescript to Python.

Change:
```python

        _mongo_db_post_install_setup = MongoDbPostInstallSetup(
            self,
            'MongoDbPostInstall',
            vpc=props.vpc,
            # vpc_subnets=mongo_vpc_subnet,
            mongo_db=mongo_db,
            users=MongoDbUsers(
                x509_auth_users=[
                    MongoDbX509User(
                        certificate=client_cert,
                        roles=json.dumps([
                            {
                                'role': 'readWriteAnyDatabase',
                                'db': 'admin'
                            },
                            {
                                'role': 'clusterMonitor',
                                'db': 'admin'
                            }
                        ])
                    )
                ]
            )
        )
```

to

```python

        _mongo_db_post_install_setup = MongoDbPostInstallSetup(
            self,
            'MongoDbPostInstall',
            vpc=props.vpc,
            # vpc_subnets=mongo_vpc_subnet,
            mongo_db=mongo_db,
            users=MongoDbUsers(
                x509_auth_users=[
                    MongoDbX509User(
                        certificate=client_cert.cert, # <<----- The change is here
                        roles=json.dumps([
                            {
                                'role': 'readWriteAnyDatabase',
                                'db': 'admin'
                            },
                            {
                                'role': 'clusterMonitor',
                                'db': 'admin'
                            }
                        ])
                    )
                ]
            )
        )
```

We'll get this fixed in our repository. Thank you again, for the report.

**Closed as completed** 2021-02-26 21:15 UTC
Labels: bug
