### ISSUE TITLE
Python: MongoDbInstance and MongoDbPostInstallSetup init params with vpc_subnets causing error

### ISSUE THREAD

**Issue by apzentral** [aws/aws-rfdk#320] opened 2021-02-21 08:11 UTC
I use example code from examples/deadline/All-In-AWS-Infrastructure-Basic/python by setting config.py `self.deploy_mongo_db: bool = True` this causing the error when passing `vpc_subnets` parameter into MongoDbInstance and MongoDbPostInstallSetup init method in storage_tier.py.

```python
availability_zone = props.vpc.availability_zones[0]

        mongo_vpc_subnet = SubnetSelection(
            subnet_type=SubnetType.PRIVATE,
            availability_zones=[availability_zone]
        ),

        mongo_db = MongoDbInstance(
            self,
            'MongoDb',
            vpc=props.vpc,
            vpc_subnets=mongo_vpc_subnet, # <--- If I comment this out, it now work
            key_name=props.key_pair_name,
            instance_type=props.database_instance_type,
            mongo_db=MongoDbApplicationProps(
                user_sspl_acceptance=props.accept_sspl_license,
                version=MongoDbVersion.COMMUNITY_3_6,
                hostname='mongo',
                dns_zone=props.dns_zone,
                server_certificate=server_cert
            )
        )

        _mongo_db_post_install_setup = MongoDbPostInstallSetup(
            self,
            'MongoDbPostInstall',
            vpc=props.vpc,
            vpc_subnets=mongo_vpc_subnet, # <--- If I comment this out, it now work
            mongo_db=mongo_db,
            users=MongoDbUsers(
                x509_auth_users=[
                    MongoDbX509User(
                        certificate=client_cert,
                        roles=json.dumps([
                            {
                                'role': 'readWriteAnyDatabase',
                                'db': 'admin'
                            },
                            {
                                'role': 'clusterMonitor',
                                'db': 'admin'
                            }
                        ])
                    )
                ]
            )
        )
```

### Reproduction Steps

Set up this project as usual and run `cdk ls`

### Error Log

`AttributeError: type object 'tuple' has no attribute '__jsii_type__'`

### Environment

  - **CDK CLI Version      : 1.90.1**
  - **CDK Framework Version: 1.86.0**
  - **RFDK Version: 0.25.0**
  - **Deadline Version: latest release**
  - **Node.js Version: v14.15.5** 
  - **OS               : Windows 10 with WSL2 Ubuntu**
  - **Language (Version): Python 3.8.5** 

### Other

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/app.py", line 133, in <module>
    main()
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/app.py", line 91, in main
    storage = storage_tier.StorageTierMongoDB(app, 'StorageTier', props=storage_props, env=env)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/storage_tier.py", line 218, in __init__
    mongo_db = MongoDbInstance(
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/aws_rfdk/__init__.py", line 2350, in __init__
    jsii.create(MongoDbInstance, self, [scope, id, props])
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 268, in create
    args=_make_reference_for_native(self, args),
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 141, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 141, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 154, in _make_reference_for_native
    "data": {
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 155, in <dictcomp>
    jsii_name: _make_reference_for_native(
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 174, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "/mnt/c/Users/karaoke/projects/github/aws-rfdk/examples/deadline/All-In-AWS-Infrastructure-Basic/python/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 267, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'tuple' has no attribute '__jsii_type__'
```

--- 

This is :bug: Bug Report

**Comment by apzentral** [comment] 2021-02-21 08:15
I also try with 

```
> cdk --version
1.86.0 (build a10cfcf)
```

and the error is the same as above.

Thank you very much for looking into this.

**Comment by ddneilson** [comment] 2021-02-22 15:33
Thanks for the report, and the great reproduction details!

**Comment by ddneilson** [comment] 2021-02-22 15:52
Looks like we have a typo in our example. This is resolved by removing an extra comma. Change:
```python
        mongo_vpc_subnet = SubnetSelection(
            subnet_type=SubnetType.PRIVATE,
            availability_zones=[availability_zone]
        ),
```
to
```python
        mongo_vpc_subnet = SubnetSelection(
            subnet_type=SubnetType.PRIVATE,
            availability_zones=[availability_zone]
        )
```

Notice the removal of the comma after the close-parenthesis.

We'll get this fixed in our repo, but that should get you past this particular error in the meantime.

**Closed as completed** 2021-02-26 21:15 UTC
Labels: bug
