### ISSUE TITLE
Please help me to solve the following error problem.  Can you write more than 64 characters in OpenSSL command?  I get the following error: problems making Certificate Request 3555938678416:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:158:maxsize=64

### ISSUE THREAD

**Issue by Shokrian** [aws/aws-rfdk#1040] opened 2023-05-05 21:56 UTC
### Environment

  - **CDK CLI Version      :**
  - **CDK Framework Version:**
  - **RFDK Version:**
  - **Deadline Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by ddneilson** [comment] 2023-05-15 22:21
Duplicate of: https://github.com/aws/aws-rfdk/issues/1039

**Closed as completed by ddneilson** 2023-05-15 22:21 UTC
Labels: bug, duplicate, needs-triage
